# -*- coding: utf-8 -*-
"""project1_RCA Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X1LH-4PxZa48MwCPYgvDc-c0FtUsG8nw
"""

#Manufacturing root cause analyzer (RCA) Agent

import pandas as pd
import numpy as np
import os
import ipywidgets as widgets
from IPython.display import display, clear_output

class RootCauseAnalyzerAgent:
    def __init__(self, base_folder='telemetry_data'):
        self.base_folder = base_folder

    def generate_synthetic_data(self):
        """Step 1: Generate 5 synthetic datasets."""
        os.makedirs(self.base_folder, exist_ok=True)

        for i in range(1, 6):
            # Baseline normal operations
            df = pd.DataFrame({
                'time': pd.date_range(start='2026-03-26', periods=100, freq='T'),
                'temperature': np.random.normal(100, 2, 100),
                'vibration': np.random.normal(10, 0.5, 100), # Baseline vibration ~10
                'chamber_pressure': np.random.normal(50, 1, 100),
                'gas_flow_sccm': np.random.normal(200, 5, 100)
            })

            # Inject anomalies to trigger our agent logic
            # Minor spikes (< 5%)
            minor_spike_idx = np.random.choice(100, 5, replace=False)
            df.loc[minor_spike_idx, 'vibration'] = df.loc[minor_spike_idx, 'vibration'] * 1.03

            # Major spikes (> 5%)
            major_spike_idx = np.random.choice(100, 3, replace=False)
            df.loc[major_spike_idx, 'vibration'] = df.loc[major_spike_idx, 'vibration'] * 1.08

            df.to_csv(os.path.join(self.base_folder, f'tool_module_{i}.csv'), index=False)

        return f"Generated 5 synthetic datasets in '{self.base_folder}'"

    def analyze_data(self, target_folder):
        """Steps 3, 4, & 5: Parse, flag, summarize, and make decisions."""
        if not os.path.exists(target_folder):
            return f"Error: Folder '{target_folder}' does not exist."

        flagged_dataframes = []

        for file in os.listdir(target_folder):
            if file.endswith('.csv') and file != 'vibration_alarm.csv':
                file_path = os.path.join(target_folder, file)
                df = pd.read_csv(file_path)

                # Calculate average vibration for the module
                vibration_avg = df['vibration'].mean()

                # Flag data > average
                flagged_df = df[df['vibration'] > vibration_avg].copy()

                if not flagged_df.empty:
                    flagged_df['source_file'] = file
                    flagged_df['vibration_avg'] = vibration_avg
                    flagged_dataframes.append(flagged_df)

        if not flagged_dataframes:
            return "No anomalies detected above average."

        # Compile summary
        summary_df = pd.concat(flagged_dataframes, ignore_index=True)

        # Step 5: Agent Decision Logic
        def make_decision(row):
            pct_increase = (row['vibration'] - row['vibration_avg']) / row['vibration_avg']
            if pct_increase < 0.05:
                return "Amp down vibrometer"
            else:
                return "Invoke RFC (Investigate Tool Module)"

        summary_df['decision'] = summary_df.apply(make_decision, axis=1)

        # Save summary
        output_path = os.path.join(target_folder, 'vibration_alarm.csv')
        summary_df.to_csv(output_path, index=False)

        return f"Analysis complete! Flagged {len(summary_df)} rows. Saved to '{output_path}'"

# --- Colab UI Setup (ipywidgets) ---
agent = RootCauseAnalyzerAgent()

# UI Elements
btn_generate = widgets.Button(description="1. Generate Data", button_style='info')
folder_input = widgets.Text(value='telemetry_data', description='Folder:')
btn_analyze = widgets.Button(description="2. Run Agent Analysis", button_style='success')
output_console = widgets.Output()

def on_generate_click(b):
    with output_console:
        clear_output()
        print(agent.generate_synthetic_data())

def on_analyze_click(b):
    with output_console:
        clear_output()
        print(agent.analyze_data(folder_input.value))

        # Display the head of the generated CSV if it exists
        if os.path.exists(os.path.join(folder_input.value, 'vibration_alarm.csv')):
            df = pd.read_csv(os.path.join(folder_input.value, 'vibration_alarm.csv'))
            display(df.head())

btn_generate.on_click(on_generate_click)
btn_analyze.on_click(on_analyze_click)

# Display UI
display(widgets.VBox([
    widgets.HTML("<h3>Manufacturing Root Cause Analyzer Agent</h3>"),
    btn_generate,
    widgets.HBox([folder_input, btn_analyze]),
    output_console
]))





